### ISSUE TITLE
Make an API so other people could add more variants

### ISSUE THREAD

**Issue by AkashiiKun** [KxmischesDomi/MoreAxolotls#1]
Hi, you might know me as i am the creator of More Axolotl Variants Mod. Your mod is way better than mine and i would like if you provide an API so i could adapt my mod as an addon of yours. Thanks.

**Comment by DomiIRL** [comment]
I could make a data driven api to add new axolotls but I don't think you should like delete your mod and only implement that api because why would you do that? Your mod works completely fine and there is now reason to do so.

**Comment by AkashiiKun** [comment]
You got me wrong, i would use your mod as an API to extend my mod, that's the point.

**Comment by DomiIRL** [comment]
What do you wanna do?

**Comment by DomiIRL** [comment]
Like what are you trying to archieve with this api what your mod currently doesn't do?

**Comment by AkashiiKun** [comment]
Basically my mod only adds new variants (and the exception of the glowxolotl that also implements a LambDynamicLights + custom sounds and particles to the variant), your mod is pretty advanced compared to mine. I don't want to "steal" your code to implement into mine, i'd rather use an API so both mods can coexists with extra compatibility.

**Comment by DomiIRL** [comment]
So you also add custom particles and sound to the glowing axolotl, mine doesn't do that. So what's more advanced at my mod?
That I also add bucket variants that are compatible with the other axolotl bucket mod and your mod?
Or that I use variant id's that are not directly after the vanilla ones to avoid problems with other mods when installed / uninstalled?
Doesn't your mod also has a forge version so you shouldn't depend on an api from a fabric only mod?

**Comment by AkashiiKun** [comment]
I'm not planning on update the forge version.

**Comment by AkashiiKun** [comment]
Also my mod adds the variants dynamically, detects the last variant number and adds the new ones after the last one in order.

**Comment by AkashiiKun** [comment]
ArrayList variants = new ArrayList<>(Arrays.asList(field_28350));

		Variant last = (Variant) variants.get(variants.size() - 1);
		int i = 1;

**Comment by vraxxda** [comment]
> Hi, you might know me as i am the creator of More Axolotl Variants Mod. Your mod is way better than mine and i would like if you provide an API so i could adapt my mod as an addon of yours. Thanks.

I think im late to quote that but, More Axolotls mod already have compatibility with your mod (mention on CurseForge page)...

So why did you need a api for?

**Comment by AkashiiKun** [comment]
Is not about compatibility but to extend my mod's features

**Comment by AkashiiKun** [comment]
Mostly the breeding features

**Comment by AkashiiKun** [comment]
Is that hard to understand? APIs are not only to do compatibility but to extend other mods' features

**Comment by AkashiiKun** [comment]
I'm using LambDynamicLights API to make glowxolotl emit light when using LDL.

**Comment by vraxxda** [comment]
> 

I understand now, thanks for explaining :) i was a lil confused

**Comment by AkashiiKun** [comment]
It's fine ^w^
