### ISSUE TITLE
Axolotl buckets only spawning in pink axolotl when displaying different axolotl

### ISSUE THREAD

**Issue by Miskept** [KxmischesDomi/MoreAxolotls#11]
The Axolotl bucket only spawns a pink axolotl when placing them down when it is e.g a glow Axolotl

**Comment by DomiIRL** [comment]
This doesn't give very much information. Pls send all your game's information since this is a bug with your modpack apparently.

**Comment by Miskept** [comment]
Yeah hold on

**Comment by Miskept** [comment]
Here's some videos of the issue.

https://user-images.githubusercontent.com/101035069/164030625-771c769c-6311-4e55-9701-ac37ac242cd4.mp4


https://user-images.githubusercontent.com/101035069/164031597-c243bd73-4e8f-4d40-8976-7e829c6d1470.mp4

**Comment by DomiIRL** [comment]
This doesn't help me. I need modlist, server log etc

**Comment by Miskept** [comment]
Modlist. Will get Serverlog
![image](https://user-images.githubusercontent.com/101035069/164033237-a9b52253-c7c8-4503-8a34-02e71df2c033.png)
![image](https://user-images.githubusercontent.com/101035069/164033304-04f4e944-86c5-4aac-924e-08dc9100f548.png)
![image](https://user-images.githubusercontent.com/101035069/164033355-323c4db7-d542-4b48-9d6e-b829bdeeabd4.png)
![image](https://user-images.githubusercontent.com/101035069/164033417-be1dee61-50af-4d5e-af68-6dd09e2c8c04.png)
![image](https://user-images.githubusercontent.com/101035069/164034695-e87dbd3d-9631-46a7-8655-507a1d644a16.png)
![image](https://user-images.githubusercontent.com/101035069/164033448-55cca39e-c1ab-4cc4-ab1f-1017acf38f60.png)
![image](https://user-images.githubusercontent.com/101035069/164033513-f1f913e6-2ccc-4146-a622-9ff3579a603d.png)
![image](https://user-images.githubusercontent.com/101035069/164034758-a5e5f2c8-0c12-4341-9fb0-b2ad5790256e.png)

**Comment by DomiIRL** [comment]
Anything in there that changes entity buckets or axolotls?

**Comment by Miskept** [comment]
Don't think there is but here is the serverlog
[latest.log](https://github.com/KxmischesDomi/MoreAxolotls/files/8514179/latest.log)

**Comment by DomiIRL** [comment]
There seems to be an exception in my code there. Maybe something changed to 1.18.2. Gonna look into that at a later time since Im working on updating all my mods to forge at the time

**Comment by Miskept** [comment]
Just a reminder is that I am using 1.18.1

**Comment by DomiIRL** [comment]
Does it work with only MoreAxolotls installed?

**Comment by DomiIRL** [comment]
Its a problem with another mod you have installed. Could you try to find the mod that causes this issue?
I'd like to fix it!
