### ISSUE TITLE
Mod generally does not work

### ISSUE THREAD

**Issue by Stalkybok** [KxmischesDomi/MoreAxolotls#16]
Whenever I go past the second  pages of the axolotl book, my game crashes. Spawn eggs do not spawn anything except vanilla axolotls. I can send the list of mods I am using if that helps.

**Comment by DomiIRL** [comment]
Does this occur in the 1.19 or 1.20 version? And do you have mavapi installed for the proper version?

**Comment by Stalkybok** [comment]
It's in 1.19.2. I have mavapi installed, and curseforge says it's the highest version of mavapi possible.

**Comment by DomiIRL** [comment]
I had your exact same issue one time and after restarting it just worked fine so I thought it was fixed. Restarting etc doesn't fix anything? And I also had it in 1.19.2 something must've broken when backporting more axolotl or mavapi.

**Comment by DomiIRL** [comment]
1.20 should work fine. It was the version I have used in development for this update

**Comment by Stalkybok** [comment]
I'll try 1.20 and get back to you.

**Comment by Stalkybok** [comment]
Actually, sadly a lot of the other mods I'm using haven't yet been updated to 1.20. Is there a way to fix it while staying on 1.19.2?

**Comment by DomiIRL** [comment]
I'll look into the issue as soon as I can. Sadly that will take a few hours since it's really late rn

**Comment by Stalkybok** [comment]
Alright, that's fair! ^-^

**Comment by DomiIRL** [comment]
So should be fixed now. The mavapi 1.19.2 had a weird issue which wasn't encountered in 1.20 for whatever reason. Just added a workaround that should indefinitly fix it. Would be thankful for someone to fully test it in combination with more axolotl :)
