### ISSUE TITLE
Cannot start server with this mod

### ISSUE THREAD

**Issue by Frost993** [KxmischesDomi/MoreAxolotls#3]
**Issue**
When I add this mod to my fabric server I cannot launch it. So I stripped it down to only Fabric API and More Axolotls but it still persists.

**Mods**
fabric-api-0.43.1+1.18.jar
more-axolotls-1.0.0-1.18.jar

**Server Log**
https://pastebin.com/ir9TzDBQ

**Comment by KxmischesDomi** [comment]
Does singleplayer work?

**Comment by DomiIRL** [comment]
Its weird because it seems like it cannot find the screen class but I guess if thats what it fails with it won't be the only thing being wrong.
I suppose that's a problem caused by something from you, that doesn't occure with any other mods?
Have you tried to reinstalling the server?

**Comment by DomiIRL** [comment]
Okay nvm I found the problem and its really really stupid, thanks for reporting this

**Comment by Frost993** [comment]
Np ;)

**Comment by DomiIRL** [comment]
Gonna upload a fixed version soon

**Comment by DomiIRL** [comment]
Fixed versions released now :)
https://www.curseforge.com/minecraft/mc-mods/more-axolotls/files
