### ISSUE TITLE
Bug with picking up Axolots from the mod

### ISSUE THREAD

**Issue by MoonSkul** [KxmischesDomi/MoreAxolotls#4]
This is a bug that I found. When I pick up an axolotl form your mod, and then place it, it becomes a normal Lucy Axolotl. Also the empty pucket that it was in now spwans a new Lucy Axolotl every time you right-click on anything except water. I downloaded the newest version of the mod for fabric.

**Comment by DomiIRL** [comment]
Thanks for reporting, I'll look into it

**Comment by DomiIRL** [comment]
Found the problem and fixed it in the newest commits.
Thank you soo much for reporting it I appreciate it

**Comment by MoonSkul** [comment]
No problem! Have a nice day!
