### ISSUE TITLE
Conflict with More Axolotl Variants Mod (1.18.1)

### ISSUE THREAD

**Issue by ghost** [KxmischesDomi/MoreAxolotls#5]
Hello! Turns out there's an incompatibility with the More Axolotl Variants Mod while playing on Fabric 1.18.1, which occurs when using /summon axolotl or finding one naturally (reported by another user, not tested personally as the spawns hated me). This happens only when using the mods in combo. When using just yours or theirs, it worked perfectly as intended. I'll report it to the mavm dev, but sadly I can only report it thru their comments so hopefully it reaches them.

Mods used:
More Axolotl Variants Mod v1.0.6 on 1.18.1 Fabric
More Axolotls 1.0.2 on 1.18.1 Fabric

The crash at hand is a ticking entity type crash:
[crash-2021-12-21_02.45.32-server.txt](https://github.com/KxmischesDomi/MoreAxolotls/files/7752417/crash-2021-12-21_02.45.32-server.txt)

Overall, not too sure who's side it's on, just wanted to let both know of the issue.

**Comment by DomiIRL** [comment]
What exactly is the problem? There shouldn’t be any problems, I tested everything before releasing and it was fine

**Comment by AkashiiKun** [comment]
Did you try with the 1.0.6 update i uploaded @KxmischesDomi? All i did was change to mojmaps and update to 1.18.

**Comment by DomiIRL** [comment]
Nope I didn’t test any new versions. You don’t modify anything on the axolotl entity don’t you?

**Comment by AkashiiKun** [comment]
I haven't.

**Comment by ghost** [comment]
Hello again! I had forgotten to mention the incompatibility was a ticking entity crash that happens whenever you do /summon axolotl, or find one naturally according to another user. As Akashii has asked, I tried mavm v1.0.5 with more-axolotls v1.0.2 and it worked perfectly, with zero crashes while summoning 200 axolotls. Something with the 1.0.6 version of mavm and ma v1.0.2 is broken when it comes to the mods' compatibilities. 

Just for the sake of redundancy, I tested the original combo of v1.0.6 and v1.0.2, and on the first /summon, a ticking entity crash happened again. Both mods (including the v1.0.5 of mavm) worked perfectly by itself.

Crash report: 
[crash-2021-12-21_09.35.47-server.txt](https://github.com/KxmischesDomi/MoreAxolotls/files/7757105/crash-2021-12-21_09.35.47-server.txt)

Sorry for any confusion from my original post, I had written it at 3am when a user in the Luna Pixel Discord reported it and was a bit tired but I wanted to bring some attention to it earlier rather than later.

**Comment by DomiIRL** [comment]
It seems that I messed up somewhere in my mixin stuff. Gonna look into that

**Comment by KxmischesDomi** [comment]
Okay yes I messed up really hard in my newest update

**Comment by KxmischesDomi** [comment]
@AkashiiKun is it possible to contact you via discord? I'd have some questions I wanna talk about in privat

**Comment by DomiIRL** [comment]
@switchnlade The problem has now been solved and @AkashiiKun is going to upload the fix on curseforge very soon
