### ISSUE TITLE
1.18.1 Server Crash.  Ticking entity.. Even after repeatedly deleting the world

### ISSUE THREAD

**Issue by tacogerbil** [KxmischesDomi/MoreAxolotls#6]
I spawn right next to the ocean and immediately upon loading in (even after multiple deletions of the world and starting over).. it crashes.
more-axolotls-1.0.2-1.18
[latest.log](https://github.com/KxmischesDomi/MoreAxolotls/files/7766427/latest.log)
[crash-2021-12-22_19.11.42-server.txt](https://github.com/KxmischesDomi/MoreAxolotls/files/7766428/crash-2021-12-22_19.11.42-server.txt)

**Comment by DomiIRL** [comment]
Like written in the description the mod is currently not compatible with mavm in the 1.18 version.
We are already working on a fix for that

![image](https://user-images.githubusercontent.com/67184131/147219292-a8f86201-b1b2-43b0-aa9d-ce8754329467.png)
