### ISSUE TITLE
Can you join a zh_cn language?

### ISSUE THREAD

**Issue by bluejt** [KxmischesDomi/MoreAxolotls#7]
I tried to translate it myself, but I couldn't use it, because once I used it, I would report an error. I don't know why

EN_CN file download address
链接：https://pan.baidu.com/s/1MYZNXZQe1m0PAt2dzBPazQ 
提取码：ncur

Hope to be recognized！

**Comment by DomiIRL** [comment]
Please upload the translation on pastebin or some other pasting website

**Comment by DomiIRL** [comment]
I don't want to download anything

**Comment by bluejt** [comment]
> 请将翻译上传到 pastebin 或其他一些粘贴网站

https://pastebin.com/Ps1fmQG9

  thank you！

**Comment by DomiIRL** [comment]
I'll probably add it in the next update when anything significant changed.
Thank you for your work.
