### ISSUE TITLE
Keeps Crashing when trying to launch the game

### ISSUE THREAD

**Issue by ghost** [KxmischesDomi/MoreAxolotls#8]
it keeps saying this message, there is no other mod on with it. 

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'more-axolotls'!
Exit Code: -1

**Comment by DomiIRL** [comment]
I need the full crash log

**Comment by DomiIRL** [comment]
And I guess you are missing the fabric api here
